name: Build & Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bharathcs2401
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bharathcs2401/hledger:latest,bharathcs2401/hledger:1.34

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: bharathcs2401
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: bharathcs2401/hledger
          short-description: ${{ github.event.repository.description }}
